### ISSUE TITLE
Unable to connect to the Beanstalkd server

### ISSUE THREAD

**Issue by ChloeCoupignyWarot** [mnapoli/phpBeanstalkdAdmin#21]
How can I connect to Beanstalkd server?

**Comment by sagikazarmark** [comment]
Can you give us a little bit more context? Any error message?

**Comment by ChloeCoupignyWarot** [comment]
![capture d ecran 2016-08-12 a 11 32 57](https://cloud.githubusercontent.com/assets/19190504/17618510/8c3f652e-6080-11e6-9fea-527d3fb8490b.png)

**Comment by mnapoli** [comment]
Are you able to connect to the server through other means? The most probable reason this doesn't work is that the server is not live, or that `myhost` is not accessible by your machine.

**Comment by ChloeCoupignyWarot** [comment]
It's okay, it was my fault the ip address had change I didn't know!
But with the real host it's working

Best regard,

Chloé Coupigny--Warot

2016-08-12 13:41 GMT+02:00 Matthieu Napoli notifications@github.com:
